-- SMMA Core Database Schema

-- Domains table: stores registered websites
CREATE TABLE IF NOT EXISTS domains (
  id TEXT PRIMARY KEY,
  url TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  primary_goal TEXT DEFAULT 'drive_traffic',
  audience_description TEXT,
  brand_voice_tone TEXT DEFAULT 'professional',
  brand_voice_formality TEXT DEFAULT 'medium',
  brand_voice_examples TEXT, -- JSON array
  brand_voice_donots TEXT,   -- JSON array
  social_accounts TEXT,       -- JSON object
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Crawled pages from domain
CREATE TABLE IF NOT EXISTS crawled_pages (
  id TEXT PRIMARY KEY,
  domain_id TEXT NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  title TEXT,
  headings TEXT,       -- JSON array
  body_text TEXT,
  internal_links TEXT, -- JSON array
  page_type TEXT,      -- home, blog, category, pricing, about, signup, other
  crawled_at TEXT DEFAULT (datetime('now'))
);

-- Domain profiles generated by SiteAnalysisAgent
CREATE TABLE IF NOT EXISTS domain_profiles (
  id TEXT PRIMARY KEY,
  domain_id TEXT NOT NULL UNIQUE REFERENCES domains(id) ON DELETE CASCADE,
  profile_data TEXT NOT NULL, -- Full DomainProfile JSON
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Competitor sets generated by CompetitorResearchAgent
CREATE TABLE IF NOT EXISTS competitor_sets (
  id TEXT PRIMARY KEY,
  domain_id TEXT NOT NULL UNIQUE REFERENCES domains(id) ON DELETE CASCADE,
  competitor_data TEXT NOT NULL, -- Full CompetitorSet JSON
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Positioning summaries generated by PositioningAgent
CREATE TABLE IF NOT EXISTS positioning_summaries (
  id TEXT PRIMARY KEY,
  domain_id TEXT NOT NULL UNIQUE REFERENCES domains(id) ON DELETE CASCADE,
  positioning_data TEXT NOT NULL, -- Full PositioningSummary JSON
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Content strategies generated by ContentStrategyAgent
CREATE TABLE IF NOT EXISTS content_strategies (
  id TEXT PRIMARY KEY,
  domain_id TEXT NOT NULL UNIQUE REFERENCES domains(id) ON DELETE CASCADE,
  strategy_data TEXT NOT NULL, -- Full ContentStrategy JSON
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Campaign calendars generated by CalendarPlannerAgent
CREATE TABLE IF NOT EXISTS campaign_calendars (
  id TEXT PRIMARY KEY,
  domain_id TEXT NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  calendar_data TEXT NOT NULL, -- Full CampaignCalendar JSON
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Individual post drafts from PostGeneratorAgent
CREATE TABLE IF NOT EXISTS post_drafts (
  id TEXT PRIMARY KEY,
  domain_id TEXT NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
  calendar_id TEXT REFERENCES campaign_calendars(id) ON DELETE CASCADE,
  calendar_post_id TEXT,
  platform TEXT NOT NULL,
  scheduled_date TEXT,
  scheduled_time TEXT,
  status TEXT DEFAULT 'draft', -- draft, approved, scheduled, published, failed
  text_content TEXT,
  variant TEXT DEFAULT 'A',
  thread TEXT,           -- JSON array for thread-style posts
  hashtags TEXT,         -- JSON array
  cta TEXT,
  media_suggestions TEXT, -- JSON array
  target_url TEXT,
  pillar_id TEXT,
  notes TEXT,
  feedback TEXT,         -- user feedback for regeneration
  published_at TEXT,
  error_message TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Social account connections
CREATE TABLE IF NOT EXISTS social_connections (
  id TEXT PRIMARY KEY,
  domain_id TEXT NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
  platform TEXT NOT NULL,
  account_name TEXT,
  access_token TEXT,     -- encrypted at rest in production
  refresh_token TEXT,
  token_expires_at TEXT,
  connected_at TEXT DEFAULT (datetime('now'))
);

-- Post analytics metrics (v1.1)
CREATE TABLE IF NOT EXISTS post_metrics (
  id TEXT PRIMARY KEY,
  post_draft_id TEXT NOT NULL REFERENCES post_drafts(id) ON DELETE CASCADE,
  impressions INTEGER DEFAULT 0,
  clicks INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  fetched_at TEXT DEFAULT (datetime('now'))
);

-- AI-generated target personas
CREATE TABLE IF NOT EXISTS personas (
  id TEXT PRIMARY KEY,
  domain_id TEXT NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  avatar_emoji TEXT DEFAULT '👤',
  demographics TEXT,        -- JSON: age_range, gender, location, income, education
  psychographics TEXT,      -- JSON: values, interests, lifestyle, attitudes
  pain_points TEXT,         -- JSON array
  motivations TEXT,         -- JSON array
  buying_triggers TEXT,     -- JSON array
  objections TEXT,          -- JSON array
  preferred_platforms TEXT, -- JSON array
  content_preferences TEXT, -- JSON: formats, topics, tone_preference
  online_behavior TEXT,     -- JSON: active_hours, content_consumption, engagement_style
  keywords TEXT,            -- JSON array of terms they use/search for
  is_primary INTEGER DEFAULT 0,
  is_ai_generated INTEGER DEFAULT 1,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_personas_domain ON personas(domain_id);

-- App settings (API keys, provider config)
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_crawled_pages_domain ON crawled_pages(domain_id);
CREATE INDEX IF NOT EXISTS idx_post_drafts_domain ON post_drafts(domain_id);
CREATE INDEX IF NOT EXISTS idx_post_drafts_calendar ON post_drafts(calendar_id);
CREATE INDEX IF NOT EXISTS idx_post_drafts_status ON post_drafts(status);
CREATE INDEX IF NOT EXISTS idx_post_drafts_platform ON post_drafts(platform);
CREATE INDEX IF NOT EXISTS idx_social_connections_domain ON social_connections(domain_id);
CREATE INDEX IF NOT EXISTS idx_post_metrics_draft ON post_metrics(post_draft_id);
